* About

This document contains my study notes and exercises over the book [[info:sicp#Top][SICP]], or the Structure and Interpretation of Computer Programs by Harold Abelson and Gerald Jay Sussman with Julie Sussman, Second Edition.

** Note about this document

This document makes use of Racket to replicate the original MIT Scheme as there is a compatible mode to access MIT Scheme within it. When the source code blocks are evaluated, their results are printed below the relevant block. The intended way to engage is to use the MELPA SICP package to provide a TeXInfo source file to read the original book directly inside of Emacs. Links to the relevant section of the TeXInfo file are included in the Org file.

** About SICP

[[https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs][Original Wikipedia article.]]

Structure and Interpretation of Computer Programs (SICP) is a computer science textbook by Massachusetts Institute of Technology professors Harold Abelson and Gerald Jay Sussman with Julie Sussman. It is known as the "Wizard Book" in hacker culture. It teaches fundamental principles of computer programming, including recursion, abstraction, modularity, and programming language design and implementation.

MIT Press published the first edition in 1984, and the second edition in 1996. It was used as the textbook for MIT's introductory course in computer science from 1984 to 2007. SICP focuses on discovering general patterns for solving specific problems, and building software systems that make use of those patterns.

MIT Press published a JavaScript version of the book in 2022.

*** Content

The book describes computer science concepts using Scheme, a dialect of Lisp. It also uses a virtual register machine and assembler to implement Lisp interpreters and compilers.

Topics in the books are:

[[info:sicp#Chapter 1][Chapter 1: Building Abstractions with Procedures]]

    - The Elements of Programming
    - Procedures and the Processes They Generate
    - Formulating Abstractions with Higher-Order Procedures

[[info:sicp#Chapter 2][Chapter 2: Building Abstractions with Data]]

    - Introduction to Data Abstraction
    - Hierarchical Data and the Closure Property
    - Symbolic Data
    - Multiple Representations for Abstract Data
    - Systems with Generic Operations

[[info:sicp#Chapter 3][Chapter 3: Modularity, Objects, and State]]

    - Assignment and Local State
    - The Environment Model of Evaluation
    - Modeling with Mutable Data
    - Concurrency: Time Is of the Essence
    - Streams

[[info:sicp#Chapter 4][Chapter 4: Metalinguistic Abstraction]]

    - The Metacircular Evaluator
    - Variations on a Scheme – Lazy Evaluation
    - Variations on a Scheme – Nondeterministic Computing
    - Logic Programming

[[info:sicp#Chapter 5][Chapter 5: Computing with Register Machines]]

    - Designing Register Machines
    - A Register-Machine Simulator
    - Storage Allocation and Garbage Collection
    - The Explicit-Control Evaluator
    - Compilation

*** Characters

Several humorously-named fictional characters appear in the book:

    - Alyssa P. Hacker, a Lisp hacker
    - Ben Bitdiddle
    - Cy D. Fect, a "reformed C programmer"
    - Eva Lu Ator
    - Lem E. Tweakit
    - Louis Reasoner, a "loose reasoner"
      
*** License

The book is licensed under a Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license.

*** Coursework

The book was used as the textbook for MIT's former introductory programming course, 6.001, from fall 1984 through its last semester, in fall 2007. Other schools also made use of the book as a course textbook.

*** Reception

Byte recommended SICP in 1986 "for professional programmers who are really interested in their profession". The magazine said that the book was not easy to read, but that it would expose experienced programmers to both old and new topics.

A review of SICP as an undergraduate textbook by Philip Wadler noted the weaknesses of the Scheme language as an introductory language for a computer science course. Wadler criticized in particular the lack of pattern matching, obscuring equational reasoning and making the teaching of proofs harder; the lack of algebraic data types in Scheme and the over-reliance on cons pairs for both code and data representation, which can confuse beginning students; and the choice of strict instead of lazy evaluation as the standard evaluation strategy.

*** Influence

SICP has been influential in computer science education, and several later books have been inspired by its style.

    - Structure and Interpretation of Classical Mechanics (SICM), another book that uses Scheme as an instructional element, by Gerald Jay Sussman and Jack Wisdom
    - Software Design for Flexibility, by Chris Hanson and Gerald Jay Sussman
    - How to Design Programs (HtDP), which intends to be a more accessible book for introductory Computer Science, and to address perceived deficiencies in SICP
    - Essentials of Programming Languages (EoPL), a book for Programming Languages courses
